### ISSUE TITLE
appdata folder

### ISSUE THREAD

**Issue by cnieuweboer** [AkiniKites/AloysAdjustments#1]
The %appdata%\Aloy's Adjustments isn't created properly by 'Aloy's **Adjustments.exe'.
If the folder doesn't already exists 'Aloy's Adjustments.exe' will fail to launch and an error.log file is created saying (with an actual username in stead of a * of course):
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ *\AppData\Roaming\Aloy's Adjustments'.

Manually creating that folder allows 'Aloy's Adjustments.exe' to run.

I am using 1.6.4.

**Comment by AkiniKites** [comment]
Fixed the issue, will be posting another release
