### ISSUE TITLE
app wont launch

### ISSUE THREAD

**Issue by MrWick01** [AkiniKites/AloysAdjustments#11]
finally been able to figure out how to download all of this (a newbie when it comes to github), I have both netcore 3.1 downloaded but everytime I try launching the exe it keeps showing the prompt to download netcore again, I deleted and reinstalled the adjustements zip again to see if that helped but nothing.

**Comment by AkiniKites** [comment]
Yeah I think .net core was a mistake because it doesn't come with windows. I've removed the need for .net core in 1.7

**Comment by MrWick01** [comment]
> 
> 
> Yeah I think .net core was a mistake because it doesn't come with windows. I've removed the need for .net core in 1.7

unfortunately now when I try to unzip it the archive is either unknown or damaged

**Comment by AkiniKites** [comment]
Are you still having this issue with the latest version?

**Comment by MrWick01** [comment]
> Are you still having this issue with the latest version?
> 

Yeah actually, I'm not sure if there's something wrong with it but chrome nor firefox allows me to complete the download, it was able to before it isn't able to now.
