### ISSUE TITLE
Unable to create pack, directory not found: temp\patch

### ISSUE THREAD

**Issue by PerchunPak** [AkiniKites/AloysAdjustments#12]
https://pastebin.com/7rwSBGf6

**Comment by Unidding** [comment]
I get the same error, if i create the folders manually it gets deleted, and the same error occurs.

**Comment by PerchunPak** [comment]
same

**Comment by AkiniKites** [comment]
What changes where you trying to apply. 
I was able to reproduce this but only if I kept everything as defaults.

**Comment by Unidding** [comment]
I have a copy of inital.bin where some of the outfits are replaced and i wanted to apply them via the patch file instead. so i loaded the modded inital.bin file and selected til the costumes that were replaced and the same costumes. 

I guess that's not how it works :-)

**Comment by PerchunPak** [comment]
i just clicked select all and click pack

**Comment by PerchunPak** [comment]
fixtd problem by not selecting few model mapping point in one package
