### ISSUE TITLE
Is it possible to disable the menu music (inventory, map, etc)?

### ISSUE THREAD

**Issue by Terenfear** [AkiniKites/AloysAdjustments#14]
I've seen lots of discussions about the menu music and how it's so repetitive that it makes ears bleed. With access to resources seems like it should be possible to just swap it out with some silent audio file, maybe add this feature to the Misc tab. What do you think?

**Comment by AkiniKites** [comment]
Heh, never even noticed, I just turned the music off. 
Added a option to disable it in 1.7.1

**Comment by Terenfear** [comment]
Hey, thanks!
