### ISSUE TITLE
Ourea in the List?

### ISSUE THREAD

**Issue by Vader5k** [AkiniKites/AloysAdjustments#15]
Hello i Love this Mod and there are so Many Characters to Play whit^^ I found a Character Called Ourea on Wiki she should be Part off Frozen Wilds

But i cant find her in the Tool ( I have all Characters shown)  Is she there or is she not Playable?

Thanks

**Comment by AkiniKites** [comment]
Sometimes the internal names don't match up with the characters, I couldn't find a good way to link the two.
Ourea should be 'DLC Prophet'

**Comment by Vader5k** [comment]
thank you its correct i dont know why but i like Ourea xd totaly Fun to play as her
