### ISSUE TITLE
Cant open app due to error

### ISSUE THREAD

**Issue by waqask64** [AkiniKites/AloysAdjustments#17]
When i try to open the program, i get an error which says... error: an attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of .net framework. This release of the .net framework does not enable cas policy by default, so this load may be dangerous. Any ideas what i did wrong? I extracted it and tried to run..

**Comment by AkiniKites** [comment]
I'll work on a fix for this. In the mean time you have to unblock the zip file before unzipping it.
Go to properties on the zip file and check the unblock checkbox at the bottom, then extract it.

![2021-02-13 20_17_53-Aloy s Adjustments-v1 7 1 zip Properties](https://user-images.githubusercontent.com/76597797/107865837-96abd680-6e38-11eb-82a5-675be9edffda.png)

**Comment by AkiniKites** [comment]
Okay its fixed in 1.7.2
