### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by Cosmad** [AkiniKites/AloysAdjustments#18]
New to GitHub, mod recommended from user on Nexus Mods. The ReadMe doesn't seem to indicate how to launch the program and I haven't found a launch button anywhere in the file structure. Is this supposed to launch automatically as soon as I press play from Steam? How do I open the program? Sorry if these are noob questions.

**Comment by AkiniKites** [comment]
No problem, sorry for the late reply. Download the zip from the releases on the right side. Extract the zip file and run the exe. If you have any troubles check the readme. Once you do the character/outfit swaps, you have to run the game from steam.
