### ISSUE TITLE
Missing Outfit? 

### ISSUE THREAD

**Issue by Madeupname722** [AkiniKites/AloysAdjustments#19]
Is it not possible to add Daradi's outfit?

![capture](https://user-images.githubusercontent.com/24537286/115050621-c6a34480-9e90-11eb-99e8-da6705c4a9f2.JPG)

**Comment by AkiniKites** [comment]
Yep she's in there. Change the filter in the top right to All Character. Her model should be called 'Character - Daradi'. Sorry for the late reply.
