### ISSUE TITLE
Adding undergarments to replacble with NPC, so the game can be played completely with a different model?

### ISSUE THREAD

**Issue by E-D-G-E** [AkiniKites/AloysAdjustments#20]
Your tool is amazing, the only thing i noticed is that you can replace all armors with any character model or any armor but you cant replace the undergarments which break the ebb and flow of the game, if it could be added then great if can't no worries, i still love your tool.

**Comment by AkiniKites** [comment]
I had that as an option originally but it broke too many cutscenes. Undergarments are treated as a special model in the game, the normal swaps don't work with them. I wasn't able to find a way around it.
