### ISSUE TITLE
Wondering if it would be possible to add the ability to increase ammo and potion inventory

### ISSUE THREAD

**Issue by astonerii** [AkiniKites/AloysAdjustments#21]
Like you can with other pouches.

I have used the HZDCoreEditor to try to find the right files to edit but was unable to do so.

**Comment by astonerii** [comment]
OK, I think I finally found the files that needed to be modded for the ammo pouches.
entities/weapons/ammo/[ammotype]/ then any file with template in the name. generally had the upgrade values in them. Along with distractrockthrown which just has a limit 10 line in it.

I extracted the files to json files using the HZDCoreEditor and made the changes in notepad to all the files.

Then I used DecimaExplorer-GUI-Repack to make all those files into a single bin file.

I named the file zPatch_ammo_upgrade.bin and put it into the Packed_DX12 directory and ran the game, but there are not changes to the game.

I am guessing I have to somehow make the game know that this new file supercedes previous file information?

here is the file if it helps.

[zPatch_ammo_upgrade.zip](https://github.com/AkiniKites/AloysAdjustments/files/6745133/zPatch_ammo_upgrade.zip)

**Comment by astonerii** [comment]
And I think I figured out where my problem is coming from.

DecimaExplorer exports core files which are semi native to the Decima engine.

HZDCoreEditor can open these files and make them look nice, but I am unable to edit any of the values in it for some reason... I can pick the values and I can type new ones but hitting enter or selecting outside the cell causes the value to revert back to the original number. And there is no save functionality that I see.

Since I am not able to edit inside the editor, the editor offers to export the files for me, which it turns into JSON files which I can edit in notepad++ and save.

That is where the problem is, the file is no longer native to decima and when I use the DecimaExplorer to repack the files I am repacking the wrong file types. JSON instead of CORE.

Am I doing something wrong such that the HZDCoreEditor does not allow me to directly edit the CORE files?

Is there a program that I can use to actually directly edit the CORE files?

**Comment by AkiniKites** [comment]
Yeah HZDCoreEditor can't edit values. You can try to edit the files using a hex editor, by searching for the guids and modifying the value nearby.
I'll see if I can add ammo/potions.

**Comment by astonerii** [comment]
Sounds awesome, thank you very much.

**Comment by AkiniKites** [comment]
This feature has been added in version 1.7.4
