### ISSUE TITLE
How to run the application

### ISSUE THREAD

**Issue by Retreock** [AkiniKites/AloysAdjustments#26]
Hello ! 

I've downloaded all the zip but the application doesn"t start. IDK why. I just have an error text. How it work ?

![Capture d’écran 2021-07-29 124740](https://user-images.githubusercontent.com/88141285/127479036-358753c7-fb92-4e57-8f58-1ac8169f2570.png)

thanks !

**Comment by AkiniKites** [comment]
Sorry for the late reply. Are you running at least version 1.7.4? I recall fixing a similar issues to this before.
