### ISSUE TITLE
UltraWeave 7.1 (original shield-weaver model)

### ISSUE THREAD

**Issue by LittleRich10** [AkiniKites/AloysAdjustments#27]
Have you been able to find the model for the UltraWeave 7.1 armor as seen on the mannequin in the bunker?
IIRC, I think you see Elizabeth wearing it in a hologram in Gaia Prime, so I think the model does exist somewhere, but I don't see it in the list.

I just like the look of the original better than Aloy's version.

Thanks for your awesome work on this mod!  It's nice to see someone make a real mod for HZD, not just a pervy nudity mod for once.

**Comment by AkiniKites** [comment]
I don't think that's possible. Its just a static object in the world it doesn't have any of the animations needed to replace a character.

I think Sony is on the same page seeing as they take down all the nude mods.
