### ISSUE TITLE
adept shield weaver

### ISSUE THREAD

**Issue by Gabbela** [AkiniKites/AloysAdjustments#30]
hi, i'm trying to buff the shield weaver armor, by giving it some modification slots.. This is the first time I#m trying to edit gamefiles myself and i cant figure out how to edit any core files extracted with decima explorer, i read in a previous issue that it wouldn't be possible with hzdeditor, since it creates an editable json file, wich can't be converted back in a core file? (please correct me if i'm wrong, as i said I'm new to editing gamefiles).
Is there any method of editing the .corefiles?
Thank you

**Comment by AkiniKites** [comment]
HzdEditor can edit game files just not using the UI. You have to make the changes programmatically, (some code that runs on startup and edits the core file as needed), recompile the editor and run it to apply your changes to the core file. Then recompress it using decimal explorer. Not the easiest process. I'm not aware of any tools that edit the files using a UI.
