### ISSUE TITLE
Requires internet connection 

### ISSUE THREAD

**Issue by Madeupname722** [AkiniKites/AloysAdjustments#35]
I am uncomfortable allowing this program to download files from the the internet in the background.

Can you please pack all the preview images into a file that can be downloaded and used locally?

![Capture](https://user-images.githubusercontent.com/24537286/146801111-d2856821-e59b-41b4-95b6-9b7d2d38ea23.JPG)

**Comment by AkiniKites** [comment]
You can disable this feature in the settings.
All images are available here: [https://github.com/AkiniKites/hzd-model-db](https://github.com/AkiniKites/hzd-model-db)
Just download the img folder and put it into [Program Folder]\data\
