### ISSUE TITLE
No longer works after Dec 2011 game patch (spinning wheel only)

### ISSUE THREAD

**Issue by Amoeba00** [AkiniKites/AloysAdjustments#36]
Game worked fine (Steam version) until they updated it with patch 1.11 back in December.
https://steamcommunity.com/app/1151640/eventcomments/3193611900734135728

Once I removed the Patch_AloysAdjustments.bin file from the Packed_DX12 folder - game started just fine.

**Comment by longjohn119** [comment]
Same problem here, the ones I made before the update hang on load and when I tried to make new patches all I got was a 1k file that does nothing. This app is for all effective purposes defunct and dead

**Comment by AkiniKites** [comment]
I've added instructions on post patch fixes. You have to clear the app's cache and rebuild the mod.
