### ISSUE TITLE
More a request: aim assist

### ISSUE THREAD

**Issue by astonerii** [AkiniKites/AloysAdjustments#38]
I am not sure if you are still working on this. But if you are, is there any way to enable aim assist in the hard modes?

Thanks if you can look into this.

I really like your tool. It makes it very easy to do upgrade updates.

**Comment by AkiniKites** [comment]
Sorry I've stopped working on this for now.
I looked into aim assist a bit and I can enable the setting but the aim assist still doesn't work. It must be disabled in a game script somewhere.

**Comment by astonerii** [comment]
Thanks! I appreciate all your work. It was very useful in making the game more enjoyable!
    On Sunday, October 16, 2022 at 10:36:44 AM EDT, AkiniKites ***@***.***> wrote:  
 
 


Sorry I've stopped working on this for now.
I looked into aim assist a bit and I can enable the setting but the aim assist still doesn't work. It must be disabled in a game script somewhere.
