### ISSUE TITLE
Works no more whit the 1.10 Hotfix + More NPCs?

### ISSUE THREAD

**Issue by Vader5k** [AkiniKites/AloysAdjustments#5]
Hello your mod is Awesome but the Game got Patched and now it does not work and the Game stuck on infinite loading screen

and can you add more NPC Charakters? I want Elida and Arana

thank you

**Comment by igor53975** [comment]
> Здравствуйте, ваш мод потрясающий, но игра была исправлена, и теперь она не работает, и игра зависает на бесконечном экране загрузки
> 
> и можно ли добавить больше персонажей NPC? Я хочу элиду и арану
> 
> благодарю вас

**filter/all characters**, will show all characters and NPCs in the game

**Comment by igor53975** [comment]
> Hello your mod is Awesome but the Game got Patched and now it does not work and the Game stuck on infinite loading screen
> 
> and can you add more NPC Charakters? I want Elida and Arana
> 
> thank you

filter/all characters, will show all characters in the game

**Comment by AkiniKites** [comment]
You have to rebuild the patch every time there is a game update. 
Patches created on previous versions of Horizon Zero Dawn will fail because the game uses a file index that gets changed whenever they release an update.
