### ISSUE TITLE
Interface elements are missing

### ISSUE THREAD

**Issue by igor53975** [AkiniKites/AloysAdjustments#6]
I did everything exactly according to the instructions, but after starting the "Aloy's Adjustments" tabs "Otfits", "Upgrades", "Misc" and "Settings" are missing.
![Screenshot_1](https://user-images.githubusercontent.com/68227373/105917348-46183900-6043-11eb-8428-a5b084af3a25.jpg)

**Comment by AkiniKites** [comment]
What version of windows are you using? Is there is an error.log file?

**Comment by igor53975** [comment]
I have already figured out the problem, the fact is that I have a 4k monitor, so the window was not displayed correctly, changed the resolution to 1280x720, and everything was immediately displayed.
Thanks.

**Comment by AkiniKites** [comment]
High DPI support has been implemented in 1.7

**Comment by igor53975** [comment]
Thanks for your work.
